### PR TITLE
Fix FormatException when parsing DateTime

### PR DESCRIPTION
**Pull request by jarmo-kauko**
Use CultureInfo.InvariantCulture when converting DateTime to string to fix FormatException when parsing in DDNAImpl.RequestSessionConfiguration

### CODE REVIEW

**Comment by Sami-Kuhakoski** [comment]
Please approve this.

**Review by Sami-Kuhakoski — APPROVED** [review]
This is needed! LGTM

**Comment by PhilCooperKing** [comment]
Thanks for the fix, is this still an issue? This repo is just a mirror, but I've raised it on internal ticket system so closing the PR.

**Comment by jarmo-kauko** [comment]
Hi. This seems to be still an issue with the latest [5.0.1-preview] - 2021-01-13. Starting the game after the first session throws an exception if system language is Finnish.

**Pull request closed without merging**
